### ISSUE TITLE
#17 broke screen size checks

### ISSUE THREAD

**Issue by tehmaze** [tehmaze/diagram#19]
```console
$ ./bin/random 100 | python diagram.py
Traceback (most recent call last):
  File "diagram.py", line 1320, in <module>
    sys.exit(run())
  File "diagram.py", line 1245, in run
    engine.consume(istream, ostream, batch=option.batch)
  File "diagram.py", line 414, in consume
    self.update([dp[0] for dp in datapoints], [dp[1] for dp in datapoints])
  File "diagram.py", line 739, in update
    self.set(point)
  File "diagram.py", line 709, in set
    self.screen[item] |= self.pixels[ry & 3][rx & 1]
  File "diagram.py", line 331, in __setitem__
    self.size.y,
OverflowError: AxisGraphScreen(622,40) overflow y = 10 > 10
```

**Comment by tehmaze** [comment]
@Lucas-C will revert your merge until this is fixed
